language: android

jdk: oraclejdk8

dist: trusty

before_install:
  - sudo apt-get update
  - sudo apt-get install npm
  - sudo npm conf set strict-ssl false
  - sudo npm cache clean -f
  - sudo npm install -g n
  - sudo n stable
  - sudo npm install -g appcenter-cli

branches:
  only:
    - master
android:
  components:
    - platform-tools
    - tools

    # Build Tools
    - build-tools-27.0.3

    # SDKs
    - android-28

    # Extras
    - extra
    - extra-android-m2repository
    - extra-android-support
    - extra-google-analytics_sdk_v2
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-17

before_script:
# Emulator Setup
#  - echo no | android create avd --force -n test -t android-17 --abi armeabi-v7a
#  - emulator -avd test -no-window &
#  - android-wait-for-emulator

script:
  - travis_wait 40 ./scripts/build.sh

env:
  global:
    - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"